# Copyright (c) 2025 René Schubotz. All rights reserved.
# Licensed under the terms specified in the LICENSE file in the project root.
r"""
HyperKAN: Hypernetwork-based KAN architecture.

This module provides an experimental KAN variant where the basis function
weights are generated by a hypernetwork conditioned on input context.
"""

from __future__ import annotations

from typing import Sequence

import tensorflow as tf

from arnold.layers.core.registry import get_layer_class

tfk = tf.keras


@tfk.utils.register_keras_serializable(package="arnold")
class HyperKAN(tfk.Model):
    r"""
    Hypernetwork-based KAN architecture.

    An experimental KAN variant where the coefficients of the basis
    expansion are generated dynamically by a hypernetwork. This allows
    the KAN to adapt its behavior based on input context.

    For input :math:`x` and context :math:`c`, the output is:

    .. math::

        y = \sum_k w_k(c) \cdot \phi_k(x)

    where :math:`w_k(c) = \text{HyperNet}(c)` generates weights conditioned
    on the context.

    Parameters
    ----------
    output_dim : int
        Output dimension.
    basis : str, default='legendre'
        Basis function type.
    degree : int, default=5
        Polynomial degree for the basis.
    hyper_hidden_dims : Sequence[int], default=(64, 32)
        Hidden layer dimensions for the hypernetwork.
    context_dim : int | None, optional
        Context input dimension. If None, uses input as context.
    basis_kwargs : dict | None, optional
        Additional kwargs for the basis layer.

    Examples
    --------
    >>> # HyperKAN with separate context
    >>> model = HyperKAN(
    ...     output_dim=1,
    ...     basis='chebyshev1',
    ...     degree=8,
    ...     context_dim=16
    ... )
    >>> # x: input, c: context
    >>> y = model([x, c])
    >>>
    >>> # HyperKAN using input as context
    >>> model = HyperKAN(output_dim=1, basis='fourier', degree=5)
    >>> y = model(x)

    Notes
    -----
    This is an experimental architecture. Performance may vary significantly
    depending on the task and hyperparameter settings.
    """

    def __init__(
        self,
        output_dim: int,
        basis: str = "legendre",
        degree: int = 5,
        hyper_hidden_dims: Sequence[int] = (64, 32),
        context_dim: int | None = None,
        basis_kwargs: dict | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.output_dim = output_dim
        self._basis_name = basis
        self.degree = degree
        self._hyper_hidden_dims = list(hyper_hidden_dims)
        self.context_dim = context_dim
        self._basis_kwargs = basis_kwargs or {}

        # Basis layer
        basis_cls = get_layer_class(basis)
        # Number of basis functions (approximate, depends on basis type)
        self._num_basis = degree + 1

        self._basis_layer = basis_cls(
            units=self._num_basis,
            degree=degree,
            **self._basis_kwargs,
        )

        # Hypernetwork: generates weights for combining basis outputs
        self._hyper_layers = []
        for dim in hyper_hidden_dims:
            self._hyper_layers.append(
                tfk.layers.Dense(dim, activation="gelu")
            )

        # Final hypernetwork layer outputs weight matrix
        self._hyper_output = tfk.layers.Dense(
            self._num_basis * output_dim,
            activation=None,
        )

    def call(
        self,
        inputs: tf.Tensor | list[tf.Tensor],
        training: bool = False,
    ) -> tf.Tensor:
        """
        Forward pass with hypernetwork-generated weights.

        Parameters
        ----------
        inputs : tf.Tensor or list[tf.Tensor]
            Either a single input tensor (used as both input and context),
            or a list [input, context] for separate context.
        training : bool
            Whether in training mode.

        Returns
        -------
        tf.Tensor
            Output tensor of shape (batch, output_dim).
        """
        if isinstance(inputs, (list, tuple)):
            x, context = inputs
        else:
            x = inputs
            context = inputs

        # Compute basis expansion: (batch, num_basis)
        phi = self._basis_layer(x, training=training)

        # Generate weights from context
        h = context
        for layer in self._hyper_layers:
            h = layer(h)

        # Output shape: (batch, num_basis * output_dim)
        weights_flat = self._hyper_output(h)

        # Reshape to (batch, num_basis, output_dim)
        weights = tf.reshape(
            weights_flat,
            [-1, self._num_basis, self.output_dim],
        )

        # Apply weights: (batch, num_basis) @ (batch, num_basis, output_dim)
        # -> (batch, output_dim)
        phi_expanded = tf.expand_dims(phi, axis=-1)  # (batch, num_basis, 1)
        output = tf.reduce_sum(phi_expanded * weights, axis=1)

        return output

    def get_config(self) -> dict:
        config = super().get_config()
        config.update(
            {
                "output_dim": self.output_dim,
                "basis": self._basis_name,
                "degree": self.degree,
                "hyper_hidden_dims": self._hyper_hidden_dims,
                "context_dim": self.context_dim,
                "basis_kwargs": self._basis_kwargs,
            }
        )
        return config

    @classmethod
    def from_config(cls, config: dict) -> "HyperKAN":
        return cls(**config)
