## Copyright (c) 2025 René Schubotz. All rights reserved.
# Licensed under the terms specified in the LICENSE file in the project root.
"""
Implementation of KAN layers and bases.
"""

from arnold.layers.core.geometric import (
    GeometricBase,
    HypersphericalHarmonics,
    SphericalHarmonics,
    Zernike,
)
from arnold.layers.core.kan_base import (
    KANBase,
    detect_hardware,
    get_recommended_dtype,
)
from arnold.layers.core.polynomial import (
    AffineQKrawtchouk,
    AlSalamCarlitz1st,
    AlSalamCarlitz2nd,
    AskeyWilson,
    AssociatedMeixnerPollaczek,
    BannaiIto,
    Bessel,
    BigQJacobi,
    Boubaker,
    Charlier,
    Chebyshev1st,
    Chebyshev2nd,
    Chebyshev3rd,
    Chebyshev4th,
    ContinuousDualHahn,
    ContinuousHahn,
    ContinuousQHermite,
    ContinuousQJacobi,
    ContinuousQLaguerre,
    ContinuousQLegendre,
    ContinuousQUltraspherical,
    DiscreteQHermite1,
    DiscreteQHermite2,
    DualHahn,
    DualQHahn,
    DualQKrawtchouk,
    Fermat,
    FermatLucas,
    Fibonacci,
    Gegenbauer,
    GeneralizedLaguerre,
    Hahn,
    Heptanacci,
    Hermite,
    Hexanacci,
    Jacobi,
    Jacobsthal,
    JacobsthalLucas,
    Krawtchouk,
    Laurent,
    Legendre,
    LittleQJacobi,
    Lucas,
    Meixner,
    Octanacci,
    Pell,
    PellLucas,
    Pentanacci,
    Pollaczek,
    PolynomialBase,
    QCharlier,
    QHahn,
    QKrawtchouk,
    QMeixner,
    QPolynomialBase,
    QRacah,
    QuantumQKrawtchouk,
    Racah,
    StieltjesWigert,
    Tetranacci,
    Tribonacci,
    Wilson,
)
from arnold.layers.core.rbf import (
    CauchyRBF,
    CubicRBF,
    ExponentialRBF,
    GaussianRBF,
    InverseMultiQuadricRBF,
    InverseQuadricRBF,
    LinearRBF,
    MultiquadricRBF,
    PowerRBF,
    RBFBase,
    ThinPlateSplineRBF,
)

# Registry API
from arnold.layers.core.registry import (
    LAYER_CATEGORIES,
    LAYER_REGISTRY,
    get_aliases,
    get_layer,
    get_layer_class,
    is_registered,
    list_layers,
    list_layers_by_category,
)
from arnold.layers.core.special import (
    Airy,
    EllipticFunctions,
    LegendreFunctions,
    Mathieu,
    ParabolicCylinder,
    Slepian,
    SpecialBase,
    Whittaker,
)
from arnold.layers.core.special import (
    Bessel as BesselFunc,  # Alias to avoid collision with Bessel polynomial
)
from arnold.layers.core.spectral import (
    CosineBasis,
    DiracComb,
    FourierKAN,
    Lorentzian,
    RandomFourierFeatures,
    SincBasis,
    SpectralBase,
    WindowedSinc,
)
from arnold.layers.core.splines import (
    BSpline,
    Cardinal,
    CatmullRom,
    SplineBase,
)
from arnold.layers.core.wavelets import (
    Bump,
    Coiflet,
    Daubechies,
    DerivativeOfGaussian,
    Haar,
    Meyer,
    Morelet,
    Poisson,
    Ricker,
    Shannon,
    Symlet,
    WaveletBase,
)


__all__ = [
    # Base classes and utilities
    "KANBase",
    "GeometricBase",
    "PolynomialBase",
    "RBFBase",
    "SplineBase",
    "SpectralBase",
    "SpecialBase",
    "WaveletBase",
    "detect_hardware",
    "get_recommended_dtype",
    # Splines
    "BSpline",
    "Cardinal",
    "CatmullRom",
    # Spectral (Phase 9b implemented)
    "CosineBasis",
    "DiracComb",
    "FourierKAN",
    "Lorentzian",
    "RandomFourierFeatures",
    "SincBasis",
    "WindowedSinc",
    # Geometric (Phase 10)
    "GeometricBase",
    "HypersphericalHarmonics",
    "SphericalHarmonics",
    "Zernike",
    # Special (Phase 11)
    "Airy",
    "BesselFunc",
    "EllipticFunctions",
    "LegendreFunctions",
    "Mathieu",
    "ParabolicCylinder",
    "Slepian",
    "Whittaker",
    # Wavelets
    "Bump",
    "Coiflet",
    "Daubechies",
    "DerivativeOfGaussian",
    "Haar",
    "Meyer",
    "Morelet",
    "Poisson",
    "Ricker",
    "Shannon",
    "Symlet",
    # Fibonacci-type polynomials
    "Fibonacci",
    "Heptanacci",
    "Hexanacci",
    "Octanacci",
    "Pentanacci",
    "Tetranacci",
    "Lucas",
    "Fermat",
    "FermatLucas",
    "Jacobsthal",
    "JacobsthalLucas",
    "Pell",
    "PellLucas",
    # Orthogonal polynomials
    "AlSalamCarlitz1st",
    "AlSalamCarlitz2nd",
    "AskeyWilson",
    "AssociatedMeixnerPollaczek",
    "BannaiIto",
    "Bessel",
    "Charlier",
    "Chebyshev1st",
    "Chebyshev2nd",
    "Chebyshev3rd",
    "Chebyshev4th",
    "Gegenbauer",
    "GeneralizedLaguerre",
    "Hermite",
    "Jacobi",
    "Legendre",
    "Pollaczek",
    "Wilson",
    # Discrete orthogonal polynomials
    "Hahn",
    "Krawtchouk",
    "Meixner",
    "Racah",
    # Continuous Hahn family (Wilson class)
    "ContinuousHahn",
    "ContinuousDualHahn",
    "DualHahn",
    "StieltjesWigert",
    # q-Hahn class (q-orthogonal polynomials) - Sprint 7E
    "QPolynomialBase",
    "QHahn",
    "BigQJacobi",
    "LittleQJacobi",
    "QMeixner",
    "QKrawtchouk",
    # q-Polynomials Part 2 - Sprint 7F
    "QCharlier",
    "QRacah",
    "DualQHahn",
    "DualQKrawtchouk",
    "AffineQKrawtchouk",
    # q-Polynomials Part 3 (Askey-Wilson Class) - Sprint 7G
    "DiscreteQHermite1",
    "DiscreteQHermite2",
    "ContinuousQHermite",
    "ContinuousQJacobi",
    "ContinuousQUltraspherical",
    # q-Polynomials Part 4 & Special - Sprint 7H
    "QuantumQKrawtchouk",
    "ContinuousQLaguerre",
    "ContinuousQLegendre",
    "Tribonacci",
    "Zernike",
    # Other polynomials
    "Boubaker",
    "Laurent",
    # RBFs
    "ExponentialRBF",
    "CauchyRBF",
    "CubicRBF",
    "GaussianRBF",
    "InverseMultiQuadricRBF",
    "InverseQuadricRBF",
    "LinearRBF",
    "MultiquadricRBF",
    "PowerRBF",
    "ThinPlateSplineRBF",
    # Registry API
    "LAYER_REGISTRY",
    "LAYER_CATEGORIES",
    "get_layer",
    "get_layer_class",
    "list_layers",
    "list_layers_by_category",
    "is_registered",
    "get_aliases",
]
