# Copyright (c) 2025 René Schubotz. All rights reserved.
# Licensed under the terms specified in the LICENSE file in the project root.
r"""
Bessel polynomials.

This module implements Bessel polynomials :math:`y_n(x)` which appear in
various signal processing and control theory applications.

Mathematical Background
-----------------------
The Bessel polynomials satisfy the three-term recurrence:

.. math::
    y_0(x) &= 1 \\
    y_1(x) &= x + 1 \\
    y_n(x) &= (2n-1) x \, y_{n-1}(x) + y_{n-2}(x), \quad n \geq 2

.. warning::
    Bessel polynomial coefficients grow rapidly and can overflow in float32
    for degrees > 15.

References
----------
.. [Wikipedia] https://en.wikipedia.org/wiki/Bessel_polynomials#Recursion
"""

import warnings

import tensorflow as tf

from arnold.utils.compilation import kan_function

from ..poly_base import PolynomialBase


tfk = tf.keras
kan_fn = kan_function()


@tfk.utils.register_keras_serializable(package="arnold", name="Bessel")
class Bessel(PolynomialBase):
    r"""
    Kolmogorov-Arnold Network layer using Bessel polynomials.

    Domain is :math:`\mathbb{R}`; coefficients grow rapidly and can overflow for
    large degrees in float32. Consider limiting ``degree`` or using float64 for
    high-order expansions.

    The Bessel polynomials are generated by the three-term recurrence relation:

    * :math:`y_{0}(x) = 1`
    * :math:`y_{1}(x) = x + 1`
    * :math:`y_{n}(x) = (2n - 1) * x * y_{n-1}(x) + y_{n-2}(x)` when n >= 2

    See also: https://en.wikipedia.org/wiki/Bessel_polynomials#Recursion
    """

    def __init__(self, degree: int, *, units: int, **kwargs):
        if degree > 15:
            warnings.warn(
                f"Bessel polynomials with degree={degree} > 15 may overflow in float32. "
                "Consider using promote_to_float64=True or reducing degree.",
                UserWarning,
                stacklevel=2,
            )
        super().__init__(degree=degree, units=units, **kwargs)

    @kan_fn
    def pseudo_vandermonde(self, x):
        # :math:`y_{0}(x) = 1`
        bessel_basis = [tf.ones_like(x)]

        if self.degree > 0:
            # :math:`y_{1}(x) = x + 1`
            bessel_basis.append(x + 1.0)

        for n in range(2, self.degree + 1):
            # :math:`y_{n}(x) = (2n - 1) * x * y_{n-1}(x) + y_{n-2}(x)` when n >= 2
            bessel_basis.append((2 * n - 1) * x * bessel_basis[n - 1] + bessel_basis[n - 2])

        return tf.stack(bessel_basis, axis=-1)

    def clenshaw_basis(self, x: tf.Tensor) -> tf.Tensor:
        x = tf.reshape(x, (-1, self.input_dim))
        y0 = tf.ones_like(x)
        if self.degree == 0:
            return tf.expand_dims(y0, -1)
        y1 = x + 1.0
        if self.degree == 1:
            return tf.stack([y0, y1], axis=-1)

        def step(carry, n):
            yn_1, yn_2 = carry
            n_f = tf.cast(n, x.dtype)
            yn = (2.0 * n_f - 1.0) * x * yn_1 + yn_2
            return (yn, yn_1)  # Only return new carry

        ns = tf.range(2, self.degree + 1)
        carries = tf.scan(step, ns, initializer=(y1, y0))
        # carries[0] has shape (degree-1, batch, input_dim) - transpose to (batch, input_dim, degree-1)
        ys = tf.transpose(carries[0], perm=[1, 2, 0])
        basis = tf.concat([tf.expand_dims(y0, -1), tf.expand_dims(y1, -1), ys], axis=-1)
        return tf.reshape(basis, (-1, self.input_dim, self.degree + 1))


__all__ = [
    "Bessel",
]
