# Copyright (c) 2025 René Schubotz. All rights reserved.
# Licensed under the terms specified in the LICENSE file in the project root.
r"""
Hermite polynomials (physicist's and probabilist's).

This module implements Hermite polynomials which are orthogonal on :math:`\mathbb{R}`.

Mathematical Background
-----------------------
The physicist's Hermite polynomials :math:`H_n(x)` satisfy:

.. math::
    H_0(x) &= 1 \\
    H_1(x) &= 2x \\
    H_{n+1}(x) &= 2x H_n(x) - 2n H_{n-1}(x)

The probabilist's Hermite polynomials :math:`He_n(x)` (normalized form) satisfy:

.. math::
    He_0(x) &= 1 \\
    He_1(x) &= x \\
    He_{n+1}(x) &= x He_n(x) - n He_{n-1}(x)

.. warning::
    Physicist's Hermite polynomials grow as :math:`O(2^n n!)` and can easily
    overflow for moderate degrees in float32.

References
----------
.. [DLMF] NIST Digital Library of Mathematical Functions, Chapter 18
   https://dlmf.nist.gov/18
"""

import warnings

import tensorflow as tf

from arnold.utils.compilation import kan_function

from ..poly_base import PolynomialBase


tfk = tf.keras
kan_fn = kan_function()


@tfk.utils.register_keras_serializable(package="arnold", name="Hermite")
class Hermite(PolynomialBase):
    r"""
    Kolmogorov-Arnold Network layer using (physicist's) Hermite polynomials.

    Domain is :math:`\mathbb{R}`; values grow approximately like :math:`2^{n}`
    so large degrees or large ``|x|`` can overflow in float32. Set ``normalized=True``
    to use probabilist's Hermite (He) which is better conditioned.

    .. warning::

        Hermite polynomials are defined on :math:`\mathbb{R}` but grow rapidly.
        For inputs with ``|x| > 5``, consider using ``input_clip=(-5, 5)`` or
        preprocessing to avoid overflow, especially at higher degrees.

    The (physicist's) Hermite polynomials are generated by the three-term recurrence relation:

    * :math:`{H_{0}(x) = 1}`
    * :math:`{H_{1}(x) = 2x}`
    * :math:`{H_{n+1}(x) = 2 * x * H_{n}(x) - 2 * n * H_{n-1}(x)}` when n >= 0

    See also: https://en.wikipedia.org/wiki/Hermite_polynomials#Recurrence_relation
    """

    def __init__(
        self,
        degree: int,
        *,
        units: int,
        normalized: bool = False,
        input_clip: tuple[float, float] | None = (-5.0, 5.0),
        **kwargs,
    ):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        normalized : bool, default False
            When True, use probabilist's Hermite polynomials :math:`He_n` (better conditioned).
            When False, use physicist's Hermite :math:`H_n`.
        input_clip : tuple[float, float] | None, default (-5.0, 5.0)
            Interval to clamp inputs. Hermite polynomials grow rapidly; clamping to
            ``[-5, 5]`` prevents overflow in typical float32 usage. Set to ``None``
            to disable clamping (use with caution).
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        if degree > 15 and not normalized:
            warnings.warn(
                f"Physicist's Hermite polynomials with degree={degree} > 15 may overflow in float32. "
                "Consider using normalized=True (probabilist's form) or promote_to_float64=True.",
                UserWarning,
                stacklevel=2,
            )
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)
        self.normalized = normalized

    @kan_fn
    def pseudo_vandermonde(self, x):
        # Probabilist's Hermite has milder growth; branch based on configuration.
        hermite_basis = [tf.ones_like(x)]

        if self.degree > 0:
            hermite_basis.append(x if self.normalized else 2.0 * x)

        for n in range(2, self.degree + 1):
            if self.normalized:
                hermite_basis.append((x * hermite_basis[n - 1]) - ((n - 1) * hermite_basis[n - 2]))
            else:
                hermite_basis.append((2.0 * x * hermite_basis[n - 1]) - (2.0 * (n - 1) * hermite_basis[n - 2]))

        return tf.stack(hermite_basis, axis=-1)

    def clenshaw_basis(self, x: tf.Tensor) -> tf.Tensor:
        # Physicist's Hermite via scan recurrence
        x = tf.reshape(x, (-1, self.input_dim))
        H0 = tf.ones_like(x)
        if self.degree == 0:
            return tf.expand_dims(H0, -1)
        H1 = x if self.normalized else 2.0 * x
        if self.degree == 1:
            return tf.stack([H0, H1], axis=-1)

        def step(carry, n):
            Hn_1, Hn_2 = carry
            n_f = tf.cast(n, x.dtype)
            if self.normalized:
                Hn = x * Hn_1 - (n_f - 1.0) * Hn_2
            else:
                Hn = 2.0 * x * Hn_1 - 2.0 * (n_f - 1.0) * Hn_2
            return (Hn, Hn_1)  # Only return new carry

        ns = tf.range(2, self.degree + 1)
        carries = tf.scan(step, ns, initializer=(H1, H0))
        # carries[0] has shape (degree-1, batch, input_dim) - transpose to (batch, input_dim, degree-1)
        Hs = tf.transpose(carries[0], perm=[1, 2, 0])
        basis = tf.concat([tf.expand_dims(H0, -1), tf.expand_dims(H1, -1), Hs], axis=-1)
        return tf.reshape(basis, (-1, self.input_dim, self.degree + 1))

    def get_config(self):
        config = super().get_config()
        config.update({"normalized": self.normalized})
        return config


__all__ = [
    "Hermite",
]
