# Copyright (c) 2025 René Schubotz. All rights reserved.
# Licensed under the terms specified in the LICENSE file in the project root.
r"""
Jacobi polynomial family: Jacobi, Legendre, Gegenbauer, and Chebyshev (1st–4th kind).

This module implements the classical Jacobi polynomial family, which are orthogonal
on :math:`[-1, 1]` with weight :math:`(1-x)^{\alpha}(1+x)^{\beta}`. Special cases:

- **Legendre**: :math:`\alpha = \beta = 0`
- **Chebyshev 1st**: :math:`\alpha = \beta = -\frac{1}{2}`
- **Chebyshev 2nd**: :math:`\alpha = \beta = \frac{1}{2}`
- **Gegenbauer**: :math:`\alpha = \beta`

Mathematical Background
-----------------------
The Jacobi polynomials :math:`P_n^{(\alpha,\beta)}(x)` satisfy the three-term recurrence:

.. math::
    P_0^{(\alpha,\beta)}(x) &= 1 \\
    P_1^{(\alpha,\beta)}(x) &= \tfrac{1}{2}(\alpha-\beta) + \tfrac{1}{2}(\alpha+\beta+2)x \\
    P_{n+1}^{(\alpha,\beta)}(x) &= (A_n x + B_n) P_n^{(\alpha,\beta)}(x) - C_n P_{n-1}^{(\alpha,\beta)}(x)

See DLMF 18.9 for recurrence coefficients.

References
----------
.. [DLMF] NIST Digital Library of Mathematical Functions, Chapter 18
   https://dlmf.nist.gov/18
"""

from abc import ABC, abstractmethod

import numpy as np
import tensorflow as tf

from arnold.utils.compilation import kan_function
from arnold.utils.constraints import softplus_lower_bound
from arnold.utils.numerics import safe_acos
from arnold.utils.weights import create_bounded_param_logits

from ..poly_base import PolynomialBase


tfk = tf.keras
kan_fn = kan_function()


@tfk.utils.register_keras_serializable(package="arnold", name="Jacobi")
class Jacobi(PolynomialBase):
    r"""
    Kolmogorov-Arnold Network layer using Jacobi polynomials.

    The Jacobi polynomials are generated by the three-term recurrence relation:
    Valid for ``alpha > -1`` and ``beta > -1`` with inputs in ``[-1, 1]`` (inputs are clipped by default).

    * :math:`J^{\alpha, \beta}_{0}(x) = 1`
    * :math:`J^{\alpha, \beta}_{1}(x) = \frac{1}{2} * (\alpha + \beta + 2) * x + \frac{1}{2} * (\alpha - \beta)`
    * :math:`J^{\alpha, \beta}_{n+1}(x) = (A^{\alpha, \beta}_{n} * x - B^{\alpha, \beta}_{n}) * J^{\alpha, \beta}_{n}(x) - C^{\alpha, \beta}_{n} * J^{\alpha, \beta}_{n-1}(x)` when n >= 1

    with

    * :math:`A^{\alpha, \beta}_{n} = \frac{(2n + \alpha + \beta +1) * (2n + \alpha + \beta + 2)}{2(n+1) * (n + \alpha + \beta + 1)}`
    * :math:`B^{\alpha, \beta}_{n} = \frac{(\beta^{2} - \alpha^{2})(2n + \alpha + \beta +1)}{2(n+1) * (n + \alpha + \beta + 1)(2n + \alpha + \beta)}`
    * :math:`C^{\alpha, \beta}_{n} = \frac{(n + \alpha)(n + \beta)(2n + \alpha + \beta + 2)}{(n+1) * (n + \alpha + \beta + 1)(2n + \alpha + \beta)}`

    Special cases of the Jacobi polynomials are:
    * the Legendre polynomials (when alpha=beta=0);
    * the Chebyshev polynomials of the first kind (when alpha=beta=-1/2);
    * the Chebyshev polynomials of the second kind (when alpha=beta==1/2);
    * the Gegenbauer polynomials (when alpha=beta)


    TODO:     Jacobi polynomials in hypergeometric representation
    :math:`J^{\alpha, \beta}_{n}(x) = \binom{n + \alpha}{n} * _2F_1(-n, n + \alpha + \beta + 1; \alpha + 1; \frac{1-x}{2})`
    """

    def __init__(
        self,
        degree: int,
        *,
        units: int,
        alpha_init: float | None = None,
        alpha_trainable=True,
        beta_init: float | None = None,
        beta_trainable=True,
        input_clip: tuple[float, float] | None = (-1.0, 1.0),
        orthonormal: bool = False,
        **kwargs,
    ):
        r"""
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        alpha_init, beta_init : float | None
            Initial parameters (must satisfy alpha, beta > -1); default RandomNormal when None.
        alpha_trainable, beta_trainable : bool
            Trainability flags.
        input_clip : tuple[float, float] | None
            Optional input clamp (defaults to [-1, 1]).
        orthonormal : bool, default False
            When True, rescales :math:`P_n^{(\\alpha,\\beta)}` to be orthonormal with respect to
            weight :math:`(1-x)^{\\alpha}(1+x)^{\\beta}` on ``[-1,1]``.
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

        self.alpha_init = alpha_init
        self.alpha_trainable = alpha_trainable
        self.beta_init = beta_init
        self.beta_trainable = beta_trainable
        self.orthonormal = orthonormal

        self.alpha_logits = None
        self.beta_logits = None

    def build(self, input_shape):
        super().build(input_shape)

        self.alpha_logits = create_bounded_param_logits(
            self, "alpha", self.alpha_init, lower_bound=-1.0, trainable=self.alpha_trainable
        )
        self.beta_logits = create_bounded_param_logits(
            self, "beta", self.beta_init, lower_bound=-1.0, trainable=self.beta_trainable
        )

    @kan_fn
    def pseudo_vandermonde(self, x):
        orig_dtype = x.dtype
        x = tf.cast(x, tf.float64)
        # softplus_lower_bound ensures alpha, beta > -1 with smooth gradients
        alpha = softplus_lower_bound(tf.cast(self.alpha_logits, tf.float64), lower_bound=-1.0)
        beta = softplus_lower_bound(tf.cast(self.beta_logits, tf.float64), lower_bound=-1.0)

        # See: http://lsec.cc.ac.cn/~hyu/teaching/shonm2013/STWchap3.2p.pdf (section 3.2.1.3)
        # :math:`J^{\alpha, \beta}_{0}(x) = 1`
        jacobi_basis = [tf.ones_like(x, dtype=tf.float64)]

        if self.degree > 0:
            # :math:`J^{\alpha, \beta}_{1}(x) = \frac{1}{2} * (\alpha + \beta + 2) * x + \frac{1}{2} * (\alpha - \beta)`
            jacobi_basis.append(0.5 * (alpha - beta) + (alpha + beta + 2) * x / 2)

        # DLMF 18.9.5: for n >= 1,
        # P_{n+1} = (a_n x + b_n) P_n - c_n P_{n-1}
        for n in range(1, self.degree):
            n_f = tf.cast(n, x.dtype)
            A_n = ((2 * n_f + alpha + beta + 1) * (2 * n_f + alpha + beta + 2)) / (
                2 * (n_f + 1) * (n_f + alpha + beta + 1)
            )
            B_n = (alpha**2 - beta**2) / ((2 * n_f + alpha + beta) * (2 * n_f + alpha + beta + 2))
            C_n = ((n_f + alpha) * (n_f + beta) * (2 * n_f + alpha + beta + 2)) / (
                (n_f + 1) * (n_f + alpha + beta + 1) * (2 * n_f + alpha + beta)
            )

            jacobi_basis.append(((A_n * x) + B_n) * jacobi_basis[n] - C_n * jacobi_basis[n - 1])

        basis = tf.stack(jacobi_basis, axis=-1)
        if self.orthonormal:
            # Norm: 2^{α+β+1} Γ(n+α+1) Γ(n+β+1) / [(2n+α+β+1) n! Γ(n+α+β+1)]
            n = tf.range(0, self.degree + 1, dtype=tf.float64)
            log2 = tf.math.log(tf.constant(2.0, dtype=tf.float64))
            log_norm = (
                (alpha + beta + 1.0) * log2
                + tf.math.lgamma(n + alpha + 1.0)
                + tf.math.lgamma(n + beta + 1.0)
                - tf.math.log(2.0 * n + alpha + beta + 1.0)
                - tf.math.lgamma(n + 1.0)
                - tf.math.lgamma(n + alpha + beta + 1.0)
            )
            scale = tf.exp(-0.5 * log_norm)
            basis = basis * scale

        return tf.cast(basis, orig_dtype)

    def clenshaw_basis(self, x: tf.Tensor) -> tf.Tensor:
        x = tf.cast(tf.reshape(x, (-1, self.input_dim)), tf.float64)
        # softplus_lower_bound ensures alpha, beta > -1 with smooth gradients
        alpha = softplus_lower_bound(tf.cast(self.alpha_logits, tf.float64), lower_bound=-1.0)
        beta = softplus_lower_bound(tf.cast(self.beta_logits, tf.float64), lower_bound=-1.0)
        orig_dtype = x.dtype

        P0 = tf.ones_like(x, dtype=tf.float64)
        if self.degree == 0:
            return tf.cast(tf.expand_dims(P0, -1), orig_dtype)
        P1 = 0.5 * (alpha - beta) + 0.5 * (alpha + beta + 2.0) * x
        if self.degree == 1:
            return tf.cast(tf.stack([P0, P1], axis=-1), orig_dtype)

        def step(carry, n):
            Pn_1, Pn_2 = carry
            n_f = tf.cast(n, x.dtype)
            # Match pseudo_vandermonde: for n=2,3,... computing P_n from P_{n-1}, P_{n-2}
            # Use (n-1) for coefficient indices since pseudo_vandermonde uses n in range(1, degree)
            n_coef = n_f - 1.0
            A_n = ((2.0 * n_coef + alpha + beta + 1.0) * (2.0 * n_coef + alpha + beta + 2.0)) / (
                2.0 * (n_coef + 1.0) * (n_coef + alpha + beta + 1.0)
            )
            B_n = (alpha**2 - beta**2) / ((2.0 * n_coef + alpha + beta) * (2.0 * n_coef + alpha + beta + 2.0))
            C_n = ((n_coef + alpha) * (n_coef + beta) * (2.0 * n_coef + alpha + beta + 2.0)) / (
                (n_coef + 1.0) * (n_coef + alpha + beta + 1.0) * (2.0 * n_coef + alpha + beta)
            )
            Pn = ((A_n * x) + B_n) * Pn_1 - C_n * Pn_2
            return (Pn, Pn_1)  # Only return new carry

        ns = tf.range(2, self.degree + 1)
        carries = tf.scan(step, ns, initializer=(P1, P0))
        # carries[0] has shape (degree-1, batch, input_dim) - the Pn values
        # Transpose to (batch, input_dim, degree-1) and concat with P0, P1
        Ps = tf.transpose(carries[0], perm=[1, 2, 0])
        basis = tf.concat([tf.expand_dims(P0, -1), tf.expand_dims(P1, -1), Ps], axis=-1)
        if self.orthonormal:
            n = tf.range(0, self.degree + 1, dtype=tf.float64)
            log2 = tf.math.log(tf.constant(2.0, dtype=tf.float64))
            log_norm = (
                (alpha + beta + 1.0) * log2
                + tf.math.lgamma(n + alpha + 1.0)
                + tf.math.lgamma(n + beta + 1.0)
                - tf.math.log(2.0 * n + alpha + beta + 1.0)
                - tf.math.lgamma(n + 1.0)
                - tf.math.lgamma(n + alpha + beta + 1.0)
            )
            scale = tf.exp(-0.5 * log_norm)
            basis = basis * scale
        return tf.cast(tf.reshape(basis, (-1, self.input_dim, self.degree + 1)), orig_dtype)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "alpha_init": self.alpha_init,
                "alpha_trainable": self.alpha_trainable,
                "beta_init": self.beta_init,
                "beta_trainable": self.beta_trainable,
                "orthonormal": self.orthonormal,
            }
        )
        return config


@tfk.utils.register_keras_serializable(package="arnold", name="Legendre")
class Legendre(PolynomialBase):
    r"""
    Kolmogorov-Arnold Network layer using Legendre polynomials.

    Legendre polynomials :math:`P_n(x)` are orthogonal on :math:`[-1, 1]` with unit weight:

    .. math::

        \int_{-1}^{1} P_m(x) \, P_n(x) \, dx = \frac{2}{2n+1} \delta_{mn}

    They satisfy the three-term recurrence:

    .. math::

        P_0(x) &= 1 \\
        P_1(x) &= x \\
        (n+1) P_{n+1}(x) &= (2n+1) \, x \, P_n(x) - n \, P_{n-1}(x)

    When ``orthonormal=True``, the basis is rescaled to:

    .. math::

        \tilde{P}_n(x) = \sqrt{\frac{2n+1}{2}} \, P_n(x)

    so that :math:`\int_{-1}^{1} \tilde{P}_m(x) \tilde{P}_n(x) dx = \delta_{mn}`.

    Notes
    -----
    Legendre polynomials are excellent for general function approximation on bounded
    intervals and have near-minimax properties. They are related to Chebyshev polynomials
    and share similar convergence characteristics for smooth functions.

    See Also
    --------
    Chebyshev1st : Often preferred for numerical stability
    Jacobi : Generalization with parameters :math:`\\alpha, \\beta`
    Gegenbauer : Special case of Jacobi with :math:`\\alpha = \\beta`

    References
    ----------
    .. [DLMF] NIST Digital Library of Mathematical Functions, Chapter 18
       https://dlmf.nist.gov/18
    .. [Wikipedia] https://en.wikipedia.org/wiki/Legendre_polynomials
    """

    def __init__(
        self,
        degree: int,
        *,
        units: int | None = None,
        output_dim: int | None = None,
        input_clip: tuple[float, float] | None = (-1.0, 1.0),
        orthonormal: bool = False,
        **kwargs,
    ):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int | None
            Output dimensionality. If omitted, ``output_dim`` is accepted for backward compatibility.
        output_dim : int | None
            Legacy alias for ``units``.
        input_clip : tuple[float, float] | None
            Interval to clip inputs to the canonical domain [-1, 1].
        orthonormal : bool, default False
            When True, rescales :math:`P_n` to :math:`\\sqrt{\\frac{2n+1}{2}} P_n` (orthonormal on ``[-1,1]``).
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        resolved_units = units if units is not None else output_dim
        super().__init__(degree=degree, units=resolved_units, input_clip=input_clip, **kwargs)
        self.orthonormal = orthonormal

    @kan_fn
    def pseudo_vandermonde(self, x):
        # :math:`P_{0}(x) = 1`
        legendre_basis = [tf.ones_like(x)]

        if self.degree > 0:
            # :math:`P_{1}(x) = x`
            legendre_basis.append(x)

        for n in range(2, self.degree + 1):
            # :math:`P_{n+1}(x) = \frac{(2n + 1) * x * P_{n}(x) - n * P_{n-1}(x)}{n+1}` when n >= 1
            legendre_basis.append((((2 * n - 1) * x * legendre_basis[n - 1]) - ((n - 1) * legendre_basis[n - 2])) / n)

        basis = tf.stack(legendre_basis, axis=-1)
        if self.orthonormal:
            n = tf.range(0, self.degree + 1, dtype=basis.dtype)
            scale = tf.sqrt((2.0 * n + 1.0) / 2.0)
            basis = basis * scale
        return basis

    def clenshaw_basis(self, x: tf.Tensor) -> tf.Tensor:
        """
        Compute Legendre basis using tf.scan for memory efficiency at high degrees.

        Uses the recurrence:
        :math:`P_{n+1}(x) = \\frac{(2n+1) x P_n(x) - n P_{n-1}(x)}{n+1}`
        """
        x = tf.reshape(x, (-1, self.input_dim))
        P0 = tf.ones_like(x)
        if self.degree == 0:
            basis = tf.expand_dims(P0, -1)
            if self.orthonormal:
                basis = basis * tf.sqrt(0.5)
            return basis
        P1 = x
        if self.degree == 1:
            basis = tf.stack([P0, P1], axis=-1)
            if self.orthonormal:
                n = tf.range(0, 2, dtype=basis.dtype)
                scale = tf.sqrt((2.0 * n + 1.0) / 2.0)
                basis = basis * scale
            return basis

        def step(carry, n):
            Pn_1, Pn_2 = carry
            n_f = tf.cast(n, x.dtype)
            # P_{n+1} = ((2n+1) x P_n - n P_{n-1}) / (n+1)
            Pn = ((2.0 * n_f + 1.0) * x * Pn_1 - n_f * Pn_2) / (n_f + 1.0)
            return (Pn, Pn_1)  # Only return new carry

        ns = tf.range(1, self.degree)  # n=1 gives P2, n=degree-1 gives P_degree
        carries = tf.scan(step, ns, initializer=(P1, P0))
        # carries[0] has shape (degree-1, batch, input_dim) - the Pn values
        # Transpose to (batch, input_dim, degree-1) and concat with P0, P1
        Ps = tf.transpose(carries[0], perm=[1, 2, 0])
        basis = tf.concat([tf.expand_dims(P0, -1), tf.expand_dims(P1, -1), Ps], axis=-1)
        if self.orthonormal:
            n = tf.range(0, self.degree + 1, dtype=basis.dtype)
            scale = tf.sqrt((2.0 * n + 1.0) / 2.0)
            basis = basis * scale
        return tf.reshape(basis, (-1, self.input_dim, self.degree + 1))

    def true_clenshaw_eval(self, x: tf.Tensor, coefficients: tf.Tensor) -> tf.Tensor:
        """
        True Clenshaw summation for Legendre polynomials with O(1) memory.

        Fuses basis computation with coefficient contraction using the Clenshaw
        recurrence for Legendre polynomials:

        .. math::

            b_{n+1} = 0, \\quad b_n = c_n \\\\
            b_{k-1} = c_{k-1} + \\frac{2k+1}{k+1} x \\cdot b_k - \\frac{k+1}{k+2} b_{k+1} \\\\
            P_0 c_0 + P_1 c_1 + \\cdots + P_n c_n = b_0

        This avoids materializing the full basis tensor, critical for high-degree
        polynomials on memory-constrained accelerators.

        :param x: Input tensor of shape (batch, input_dim).
        :param coefficients: Coefficient tensor of shape (input_dim, degree+1, output_dim).
        :returns: Output tensor of shape (batch, output_dim).
        """
        # Reshape x for computation: (batch, input_dim)
        x = tf.reshape(x, (-1, self.input_dim))  # (B, D)
        
        # coefficients: (input_dim, degree+1, output_dim)
        degree = self.degree
        
        # Apply orthonormal scaling to coefficients if needed
        if self.orthonormal:
            n = tf.range(0, degree + 1, dtype=coefficients.dtype)
            scale = tf.sqrt((2.0 * n + 1.0) / 2.0)
            # scale: (degree+1,) -> (1, degree+1, 1) for broadcasting
            coefficients = coefficients * tf.reshape(scale, (1, -1, 1))
        
        # Legendre Clenshaw recurrence (backward):
        # b_{k} = c_k + alpha_k * x * b_{k+1} - beta_{k+1} * b_{k+2}
        # where alpha_k = (2k+1)/(k+1), beta_{k+1} = (k+1)/(k+2)
        
        # Initialize: b_{n+1} = 0, b_n = c_n
        batch_size = tf.shape(x)[0]
        output_dim = tf.shape(coefficients)[-1]
        
        b_next2 = tf.zeros((batch_size, self.input_dim, output_dim), dtype=coefficients.dtype)
        b_next1 = tf.broadcast_to(
            tf.expand_dims(coefficients[:, degree, :], 0),  # (1, D, O)
            (batch_size, self.input_dim, output_dim)
        )
        
        # x for broadcasting: (B, D) -> (B, D, 1)
        x_expanded = tf.expand_dims(x, -1)
        
        def clenshaw_step(carry, k):
            b_next1, b_next2 = carry
            k_f = tf.cast(k, coefficients.dtype)
            
            # Coefficients for Legendre recurrence
            alpha = (2.0 * k_f + 1.0) / (k_f + 1.0)  # (2k+1)/(k+1)
            beta = (k_f + 1.0) / (k_f + 2.0)  # (k+1)/(k+2)
            
            # c_k coefficient
            c_k = coefficients[:, k, :]  # (D, O)
            c_k = tf.broadcast_to(tf.expand_dims(c_k, 0), tf.shape(b_next1))
            
            # b_k = c_k + alpha_k * x * b_{k+1} - beta_{k+1} * b_{k+2}
            b_new = c_k + alpha * x_expanded * b_next1 - beta * b_next2
            
            return (b_new, b_next1)
        
        # Run recurrence from k = degree-1 down to k = 0
        if degree > 0:
            ks = tf.range(degree - 1, -1, -1)  # degree-1, degree-2, ..., 0
            (b_0, _) = tf.foldl(clenshaw_step, ks, initializer=(b_next1, b_next2))
        else:
            b_0 = b_next1
        
        # For Legendre, the result is simply b_0 (P_0(x) = 1)
        # Sum over input dimensions: (B, D, O) -> (B, O)
        output = tf.reduce_sum(b_0, axis=1)
        
        return output

    def get_config(self):
        config = super().get_config()
        config.update({"orthonormal": self.orthonormal})
        return config


@tfk.utils.register_keras_serializable(package="arnold", name="Gegenbauer")
class Gegenbauer(PolynomialBase):
    r"""
    Kolmogorov-Arnold Network layer using Gegenbauer polynomials.

    The Gegenbauer polynomials are generated by the three-term recurrence relation:
    valid for ``alpha > -0.5`` with inputs on ``[-1, 1]`` (inputs are clipped by default).

    * :math:`C^{\alpha}_{0}(x) = 1`
    * :math:`C^{\alpha}_{1}(x) = 2 * \alpha * x`
    * :math:`C^{\alpha}_{n+1}(x) = \frac{(2 * (n + \alpha) * x * C^{\alpha}_{n}(x)) - ((n + 2 * \alpha - 1) * C^{\alpha}_{n - 1}(x))}{n + 1}` when n >= 1

    See also: https://en.wikipedia.org/wiki/Gegenbauer_polynomials#Characterizations

    They generalize Legendre polynomials and Chebyshev polynomials, and are special cases of Jacobi polynomials.
    """

    def __init__(
        self,
        degree: int,
        *,
        units: int,
        alpha_init: float | None = None,
        alpha_trainable: bool = True,
        input_clip: tuple[float, float] | None = (-1.0, 1.0),
        orthonormal: bool = False,
        **kwargs,
    ):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        alpha_init : float | None
            Initial value for ``alpha``; must satisfy ``alpha > -0.5``; defaults to RandomNormal when None.
        alpha_trainable : bool
            Whether ``alpha`` is trainable.
        input_clip : tuple[float, float] | None
            Optional input clamp (defaults to [-1, 1]).
        orthonormal : bool, default False
            When True, rescales :math:`C_n^{\\alpha}` to be orthonormal with respect to
            weight :math:`(1-x^2)^{\\alpha-1/2}` on ``[-1,1]``.
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

        self.alpha_init = alpha_init
        self.alpha_trainable = alpha_trainable
        self.orthonormal = orthonormal
        self.alpha_logits = None

    def build(self, input_shape):
        super().build(input_shape)
        self.alpha_logits = create_bounded_param_logits(
            self, "alpha", self.alpha_init, lower_bound=-0.5, trainable=self.alpha_trainable
        )

    @kan_fn
    def pseudo_vandermonde(self, x):
        # :math:`C^{\alpha}_{0}(x) = 1`
        # softplus_lower_bound ensures alpha > -0.5 with smooth gradients
        alpha = softplus_lower_bound(tf.cast(self.alpha_logits, x.dtype), lower_bound=-0.5)
        gegenbauer_basis = [tf.ones_like(x)]

        if self.degree > 0:
            # :math:`C^{\alpha}_{1}(x) = 2 * \alpha x`
            gegenbauer_basis.append(2 * alpha * x)

        for n in range(2, self.degree + 1):
            # :math:`C^{\alpha}_{n+1}(x) = \frac{(2 * (n + \alpha) * x * C^{\alpha}_{n}(x)) - ((n + 2 * \alpha - 1) * C^{\alpha}_{n - 1}(x))}{n + 1}` when n >= 1
            gegenbauer_basis.append(
                (
                    (2 * ((n - 1) + alpha) * x * gegenbauer_basis[n - 1])
                    - (((n - 1) + 2 * alpha - 1) * gegenbauer_basis[n - 2])
                )
                / n
            )

        basis = tf.stack(gegenbauer_basis, axis=-1)
        if self.orthonormal:
            # norm = π 2^{1-2α} Γ(n+2α)/(n!(n+α) Γ(α)^2)
            n = tf.range(0, self.degree + 1, dtype=basis.dtype)
            alpha = tf.cast(alpha, basis.dtype)
            log_norm = (
                tf.math.log(np.pi)
                + (1.0 - 2.0 * alpha) * tf.math.log(2.0)
                + tf.math.lgamma(n + 2.0 * alpha)
                - tf.math.lgamma(n + 1.0)
                - tf.math.log(n + alpha)
                - 2.0 * tf.math.lgamma(alpha)
            )
            scale = tf.exp(-0.5 * log_norm)
            basis = basis * scale
        return basis

    def clenshaw_basis(self, x: tf.Tensor) -> tf.Tensor:
        x = tf.reshape(x, (-1, self.input_dim))
        C0 = tf.ones_like(x)
        if self.degree == 0:
            return tf.expand_dims(C0, -1)
        # softplus_lower_bound ensures alpha > -0.5 with smooth gradients
        alpha = softplus_lower_bound(tf.cast(self.alpha_logits, x.dtype), lower_bound=-0.5)
        C1 = 2.0 * alpha * x
        if self.degree == 1:
            return tf.stack([C0, C1], axis=-1)

        def step(carry, n):
            Cn_1, Cn_2 = carry
            n_f = tf.cast(n, x.dtype)
            # Match pseudo_vandermonde: for n=2,3,... computing C_n from C_{n-1}, C_{n-2}
            # C_n = (2*(n-1+alpha)*x*C_{n-1} - (n-1+2*alpha-1)*C_{n-2}) / n
            Cn = ((2.0 * (n_f - 1.0 + alpha) * x * Cn_1) - ((n_f - 1.0 + 2.0 * alpha - 1.0) * Cn_2)) / n_f
            return (Cn, Cn_1)  # Only return new carry

        ns = tf.range(2, self.degree + 1)
        carries = tf.scan(step, ns, initializer=(C1, C0))
        # carries[0] has shape (degree-1, batch, input_dim) - transpose to (batch, input_dim, degree-1)
        Cs = tf.transpose(carries[0], perm=[1, 2, 0])
        basis = tf.concat([tf.expand_dims(C0, -1), tf.expand_dims(C1, -1), Cs], axis=-1)
        if self.orthonormal:
            n = tf.range(0, self.degree + 1, dtype=basis.dtype)
            alpha = tf.cast(alpha, basis.dtype)
            log_norm = (
                tf.math.log(np.pi)
                + (1.0 - 2.0 * alpha) * tf.math.log(2.0)
                + tf.math.lgamma(n + 2.0 * alpha)
                - tf.math.lgamma(n + 1.0)
                - tf.math.log(n + alpha)
                - 2.0 * tf.math.lgamma(alpha)
            )
            scale = tf.exp(-0.5 * log_norm)
            basis = basis * scale
        return tf.reshape(basis, (-1, self.input_dim, self.degree + 1))

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "alpha_init": self.alpha_init,
                "alpha_trainable": self.alpha_trainable,
                "orthonormal": self.orthonormal,
            }
        )
        return config


@tfk.utils.register_keras_serializable(package="arnold", name="Chebyshev")
class Chebyshev(PolynomialBase, ABC):
    r"""
    Abstract base class for Kolmogorov-Arnold Network layer using Chebyshev polynomial basis.

    TODO: check https://www.mathematik.uni-kassel.de/~koepf/Publikationen/cheby.pdf
    """

    def __init__(self, *args, **kwargs):
        r"""
        :param input_dim: This layers input size
        :type input_dim: int

        :param output_dim: This layers output size
        :type output_dim: int

        :param degree: The maximum degree of the polynomial basis element (default is 3).
        :type degree: int

        :param decompose_weights: Whether or not to represent the polynomial_coefficients weights tensor as a learnable Tucker decomposition. Default to False.
        :type decompose_weights: bool

        :param core_ranks: A 3-tuple of non-zero, positive integers giving the ranks of the Tucker decomposition core tensor. Ignored if `decompose_weights` is False; defaults to None.
        :type core_ranks: None | Tuple[int, int, int]

        :param tanh_x: Flag indicating whether to normalize any input to [-1, 1] using tanh before further processing.
        :type tanh_x: bool
        """
        super().__init__(*args, **kwargs)
        self.arange = tf.constant(tf.range(0, self.degree + 1, 1, dtype=float))

    @abstractmethod
    def pseudo_vandermonde(self, x):
        """Compute Chebyshev basis; implemented by subclasses."""
        raise NotImplementedError


@tfk.utils.register_keras_serializable(package="arnold", name="Chebyshev1st")
class Chebyshev1st(Chebyshev):
    r"""
    Chebyshev polynomials of the first kind in trigonometric form.

    .. math::

        T_n(x) = \cos(n \arccos(x)), \quad |x| \le 1

    Inputs are clipped to the canonical domain ``[-1, 1]`` by default.
    """

    def __init__(self, degree: int, *, units: int, input_clip: tuple[float, float] | None = (-1.0, 1.0), **kwargs):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        input_clip : tuple[float, float] | None
            Interval to clamp inputs before evaluating ``acos`` (defaults to [-1, 1]).
        orthonormal : bool, default False
            When True, rescales :math:`T_n` by :math:`\\sqrt{2/\\pi}` (and :math:`1/\\sqrt{\\pi}` for ``n=0``)
            to make the basis orthonormal with respect to weight :math:`1/\\sqrt{1-x^2}` on ``[-1,1]``.
        **kwargs :
            Forwarded to :class:`PolynomialBase` (e.g., activation, use_bias).
        """
        self.orthonormal = kwargs.pop("orthonormal", False)
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

    @kan_fn
    def pseudo_vandermonde(self, x):
        # Use broadcasting instead of tf.tile for better performance
        x = tf.reshape(x, (-1, self.input_dim, 1))  # (B, D, 1)
        theta = safe_acos(x)  # (B, D, 1)
        # arange broadcasts: (1, 1, degree+1) * (B, D, 1) -> (B, D, degree+1)
        basis = tf.math.cos(theta * self.arange)
        if self.orthonormal:
            n = tf.range(0, self.degree + 1, dtype=basis.dtype)
            scale = tf.where(n == 0, tf.sqrt(1.0 / tf.constant(np.pi, dtype=basis.dtype)), tf.sqrt(2.0 / tf.constant(np.pi, dtype=basis.dtype)))
            basis = basis * scale
        return basis

    def clenshaw_basis(self, x: tf.Tensor) -> tf.Tensor:
        theta = safe_acos(tf.reshape(x, (-1, self.input_dim)))
        cos_theta = tf.cos(theta)
        T0 = tf.ones_like(theta)
        if self.degree == 0:
            return tf.expand_dims(T0, axis=-1)
        T1 = cos_theta
        if self.degree == 1:
            return tf.stack([T0, T1], axis=-1)

        def step(carry, _n):
            Tn_1, Tn_2 = carry
            Tn = 2.0 * cos_theta * Tn_1 - Tn_2
            return (Tn, Tn_1)  # Only return new carry

        ns = tf.range(2, self.degree + 1)
        carries = tf.scan(step, ns, initializer=(T1, T0))
        # carries[0] has shape (degree-1, batch, input_dim) - transpose to (batch, input_dim, degree-1)
        Ts = tf.transpose(carries[0], perm=[1, 2, 0])
        basis = tf.concat([tf.expand_dims(T0, -1), tf.expand_dims(T1, -1), Ts], axis=-1)
        if self.orthonormal:
            n = tf.range(0, self.degree + 1, dtype=basis.dtype)
            scale = tf.where(n == 0, tf.sqrt(1.0 / tf.constant(np.pi, dtype=basis.dtype)), tf.sqrt(2.0 / tf.constant(np.pi, dtype=basis.dtype)))
            basis = basis * scale
        return tf.reshape(basis, (-1, self.input_dim, self.degree + 1))

    def true_clenshaw_eval(self, x: tf.Tensor, coefficients: tf.Tensor) -> tf.Tensor:
        """
        True Clenshaw summation for Chebyshev polynomials with O(1) memory.

        Fuses basis computation with coefficient contraction using the Clenshaw
        recurrence for Chebyshev polynomials:

        .. math::

            b_{n+1} = 0, \\quad b_n = c_n \\\\
            b_{k-1} = c_{k-1} + 2x \\cdot b_k - b_{k+1} \\\\
            T_0 c_0 + T_1 c_1 + \\cdots + T_n c_n = b_0 - x \\cdot b_1

        This avoids materializing the full basis tensor, critical for high-degree
        polynomials on memory-constrained accelerators.

        :param x: Input tensor of shape (batch, input_dim).
        :param coefficients: Coefficient tensor of shape (input_dim, degree+1, output_dim).
        :returns: Output tensor of shape (batch, output_dim).
        """
        # Reshape x for computation: (batch, input_dim)
        x = tf.reshape(x, (-1, self.input_dim))  # (B, D)
        cos_x = tf.cos(safe_acos(x))  # Use acos for Chebyshev domain
        
        # coefficients: (input_dim, degree+1, output_dim)
        degree = self.degree
        
        # Apply orthonormal scaling to coefficients if needed
        if self.orthonormal:
            n = tf.range(0, degree + 1, dtype=coefficients.dtype)
            scale = tf.where(
                n == 0,
                tf.sqrt(1.0 / tf.constant(np.pi, dtype=coefficients.dtype)),
                tf.sqrt(2.0 / tf.constant(np.pi, dtype=coefficients.dtype))
            )
            # scale: (degree+1,) -> (1, degree+1, 1) for broadcasting
            coefficients = coefficients * tf.reshape(scale, (1, -1, 1))
        
        # Clenshaw recurrence: b_{k-1} = c_{k-1} + 2*cos_x*b_k - b_{k+1}
        # Start with b_{n+1} = 0, b_n = c_n
        # coefficients[:, k, :] is c_k for all input dims and output dims
        
        # Initialize: b_{n+1} = 0, b_n = c_n
        # Shape: (B, D, O) where O is output_dim
        b_next = tf.zeros((tf.shape(x)[0], self.input_dim, tf.shape(coefficients)[-1]), dtype=coefficients.dtype)
        b_curr = tf.broadcast_to(
            tf.expand_dims(coefficients[:, degree, :], 0),  # (1, D, O)
            (tf.shape(x)[0], self.input_dim, tf.shape(coefficients)[-1])
        )
        
        # cos_x for Chebyshev: (B, D) -> (B, D, 1) for broadcasting
        cos_x_expanded = tf.expand_dims(cos_x, -1)
        
        def clenshaw_step(carry, k):
            b_curr, b_next = carry
            # c_{k-1} + 2*cos_x*b_k - b_{k+1}
            c_k = coefficients[:, k, :]  # (D, O) -> broadcast to (B, D, O)
            c_k = tf.broadcast_to(tf.expand_dims(c_k, 0), tf.shape(b_curr))
            b_new = c_k + 2.0 * cos_x_expanded * b_curr - b_next
            return (b_new, b_curr)
        
        # Run recurrence from k = degree-1 down to k = 0
        if degree > 0:
            ks = tf.range(degree - 1, -1, -1)  # degree-1, degree-2, ..., 0
            (b_0, b_1) = tf.foldl(clenshaw_step, ks, initializer=(b_curr, b_next))
        else:
            b_0, b_1 = b_curr, b_next
        
        # Final result: b_0 - cos_x * b_1
        result = b_0 - cos_x_expanded * b_1
        
        # Sum over input dimensions: (B, D, O) -> (B, O)
        output = tf.reduce_sum(result, axis=1)
        
        return output

    def get_config(self):
        config = super().get_config()
        config.update({"orthonormal": self.orthonormal})
        return config


@tfk.utils.register_keras_serializable(package="arnold", name="Chebyshev2nd")
class Chebyshev2nd(Chebyshev):
    r"""
    Kolmogorov-Arnold Network layer using 2nd kind Chebyshev polynomials in trigonometric formulation

    .. math::
        :nowrap:

        \begin{equation}
        U_{n}(x) = \frac{\sin((n+1) * \arccos(x))}{\sin(\arccos(x))}, \, \lvert x \rvert \leq 1
        \end{equation}

    See: https://core.ac.uk/download/pdf/82763706.pdf

    Stable on ``[-1, 1]``; inputs are clipped by default to avoid ``acos``/``sin``
    singularities at the boundaries.
    """

    def __init__(self, degree: int, *, units: int, input_clip: tuple[float, float] | None = (-1.0, 1.0), orthonormal: bool = False, **kwargs):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        input_clip : tuple[float, float] | None
            Interval to clamp inputs before evaluating ``acos`` (defaults to [-1, 1]).
        orthonormal : bool, default False
            When True, rescales :math:`U_n` by :math:`\\sqrt{2/\\pi}` (orthonormal with respect to weight ``sqrt(1-x^2)`` on ``[-1,1]``).
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        self.orthonormal = orthonormal
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

    @kan_fn
    def pseudo_vandermonde(self, x):
        # Use broadcasting instead of tf.tile for better performance
        x = tf.reshape(x, (-1, self.input_dim, 1))  # (B, D, 1)
        theta = safe_acos(x)  # (B, D, 1)
        k = tf.cast(tf.range(1, self.degree + 2), theta.dtype)  # 1..degree+1
        k = tf.reshape(k, (1, 1, -1))  # (1, 1, degree+1)
        # Broadcasting: (B, D, 1) * (1, 1, degree+1) -> (B, D, degree+1)
        num = tf.math.sin(theta * k)
        den = tf.math.sin(theta)
        is_boundary = tf.abs(den) < 1e-8
        sign = tf.where(x >= 0, tf.ones_like(x), -tf.ones_like(x))
        boundary_val = tf.pow(sign, k - 1.0) * k
        safe_den = tf.where(is_boundary, tf.ones_like(den), den)
        normal = num / safe_den
        basis = tf.where(is_boundary, boundary_val, normal)
        if self.orthonormal:
            scale = tf.sqrt(2.0 / tf.constant(np.pi, dtype=basis.dtype))
            basis = basis * scale
        return basis

    def clenshaw_basis(self, x: tf.Tensor) -> tf.Tensor:
        theta = safe_acos(tf.reshape(x, (-1, self.input_dim)))
        U0 = tf.ones_like(theta)
        if self.degree == 0:
            return tf.expand_dims(U0, -1)
        U1 = 2.0 * tf.cos(theta)
        if self.degree == 1:
            return tf.stack([U0, U1], axis=-1)

        def step(carry, _n):
            Un_1, Un_2 = carry
            Un = 2.0 * tf.cos(theta) * Un_1 - Un_2
            return (Un, Un_1)  # Only return new carry

        ns = tf.range(2, self.degree + 1)
        carries = tf.scan(step, ns, initializer=(U1, U0))
        # carries[0] has shape (degree-1, batch, input_dim) - transpose to (batch, input_dim, degree-1)
        Us = tf.transpose(carries[0], perm=[1, 2, 0])
        basis = tf.concat([tf.expand_dims(U0, -1), tf.expand_dims(U1, -1), Us], axis=-1)
        if self.orthonormal:
            scale = tf.sqrt(2.0 / tf.constant(np.pi, dtype=basis.dtype))
            basis = basis * scale
        return tf.reshape(basis, (-1, self.input_dim, self.degree + 1))

    def get_config(self):
        config = super().get_config()
        config.update({"orthonormal": self.orthonormal})
        return config


@tfk.utils.register_keras_serializable(package="arnold", name="Chebyshev3rd")
class Chebyshev3rd(Chebyshev):
    r"""
    Kolmogorov-Arnold Network layer using 3rd kind Chebyshev polynomials in trigonometric formulation

    .. math::
        :nowrap:

        \begin{equation}
        V_{n}(x) = \frac{\cos((n + \tfrac{1}{2}) * \arccos(x))}{\cos(\tfrac{1}{2} * \arccos(x))}, \, \lvert x \rvert \leq 1
        \end{equation}

    See: https://core.ac.uk/download/pdf/82763706.pdf

    Stable on ``[-1, 1]``; inputs are clipped by default to avoid ``acos``/``cos``
    singularities at the boundaries.
    """

    def __init__(self, degree: int, *, units: int, input_clip: tuple[float, float] | None = (-1.0, 1.0), **kwargs):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        input_clip : tuple[float, float] | None
            Interval to clamp inputs before evaluating ``acos`` (defaults to [-1, 1]).
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

    @kan_fn
    def pseudo_vandermonde(self, x):
        # Use broadcasting instead of tf.tile for better performance
        x = tf.reshape(x, (-1, self.input_dim, 1))  # (B, D, 1)
        theta = safe_acos(x)  # (B, D, 1)
        k = tf.range(0, self.degree + 1, dtype=theta.dtype) + 0.5  # (degree+1,)
        k = tf.reshape(k, (1, 1, -1))  # (1, 1, degree+1)
        # Broadcasting: (B, D, 1) * (1, 1, degree+1) -> (B, D, degree+1)
        num = tf.math.cos(theta * k)
        den = tf.math.cos(0.5 * theta)
        den = tf.where(tf.abs(den) < 1e-8, tf.ones_like(den), den)
        return num / den


@tfk.utils.register_keras_serializable(package="arnold", name="Chebyshev4th")
class Chebyshev4th(Chebyshev):
    r"""
    Kolmogorov-Arnold Network layer using 4th kind Chebyshev polynomials in trigonometric formulation

    .. math::
        :nowrap:

        \begin{equation}
        W_{n}(x) = \frac{\sin((n + \tfrac{1}{2}) * \arccos(x))}{\sin(\tfrac{1}{2} * \arccos(x))}, \, \lvert x \rvert \leq 1
        \end{equation}

    See: https://core.ac.uk/download/pdf/82763706.pdf

    Stable on ``[-1, 1]``; inputs are clipped by default to avoid ``acos``/``sin``
    singularities at the boundaries.
    """

    def __init__(self, degree: int, *, units: int, input_clip: tuple[float, float] | None = (-1.0, 1.0), **kwargs):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        input_clip : tuple[float, float] | None
            Interval to clamp inputs before evaluating ``acos`` (defaults to [-1, 1]).
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

    @kan_fn
    def pseudo_vandermonde(self, x):
        # Use broadcasting instead of tf.tile for better performance
        x = tf.reshape(x, (-1, self.input_dim, 1))  # (B, D, 1)
        theta = safe_acos(x)  # (B, D, 1)
        k = tf.range(0, self.degree + 1, dtype=theta.dtype) + 0.5  # (degree+1,)
        k = tf.reshape(k, (1, 1, -1))  # (1, 1, degree+1)
        # Broadcasting: (B, D, 1) * (1, 1, degree+1) -> (B, D, degree+1)
        num = tf.math.sin(theta * k)
        den = tf.math.sin(0.5 * theta)
        den = tf.where(tf.abs(den) < 1e-8, tf.ones_like(den), den)
        return num / den


# Aliases for backward compatibility
Ultraspherical = Gegenbauer


__all__ = [
    "Jacobi",
    "Legendre",
    "Gegenbauer",
    "Ultraspherical",
    "Chebyshev",
    "Chebyshev1st",
    "Chebyshev2nd",
    "Chebyshev3rd",
    "Chebyshev4th",
]
