# Copyright (c) 2025 René Schubotz. All rights reserved.
# Licensed under the terms specified in the LICENSE file in the project root.
r"""
Generalized Laguerre polynomials.

This module implements Laguerre polynomials :math:`L_n^{(\alpha)}(x)` which are
orthogonal on :math:`[0, \infty)` with weight :math:`x^{\alpha} e^{-x}`.

Mathematical Background
-----------------------
The generalized Laguerre polynomials satisfy the three-term recurrence:

.. math::
    L_0^{(\alpha)}(x) &= 1 \\
    L_1^{(\alpha)}(x) &= 1 + \alpha - x \\
    (n+1) L_{n+1}^{(\alpha)}(x) &= (2n+1+\alpha-x) L_n^{(\alpha)}(x) - (n+\alpha) L_{n-1}^{(\alpha)}(x)

The special case :math:`\alpha = 0` gives the standard Laguerre polynomials.

References
----------
.. [DLMF] NIST Digital Library of Mathematical Functions, Chapter 18
   https://dlmf.nist.gov/18
"""

import tensorflow as tf

from arnold.utils.compilation import kan_function
from arnold.utils.constraints import softplus_lower_bound
from arnold.utils.weights import create_bounded_param_logits

from ..poly_base import PolynomialBase


tfk = tf.keras
kan_fn = kan_function()


@tfk.utils.register_keras_serializable(package="arnold", name="GeneralizedLaguerre")
class GeneralizedLaguerre(PolynomialBase):
    r"""
    Kolmogorov-Arnold Network layer using Laguerre polynomials.

    The generalized Laguerre polynomials are generated by the three-term recurrence relation:
    The orthogonality interval is :math:`[0, \infty)` with weight :math:`x^{\alpha} e^{-x}`; ``alpha`` must satisfy ``alpha > -1``.

    * :math:`L^{\alpha}_{0}(x) = 1`
    * :math:`L^{\alpha}_{1}(x) = 1 + \alpha - x`
    * :math:`L^{\alpha}_{n+1}(x) = \frac{(2n + 1 + \alpha - x) * L^{\alpha}_{n}(x) - (n + \alpha) * L^{\alpha}_{n-1}(x)}{n+1}` when n >= 1

    Special cases of the  generalized Laguerre polynomials are:
    * the Laguerre polynomials (when alpha=0);

    See also: https://en.wikipedia.org/wiki/Laguerre_polynomials#Generalized_Laguerre_polynomials
    """

    def __init__(
        self,
        degree: int,
        *,
        units: int,
        alpha_init: float | None = None,
        alpha_trainable: bool = True,
        normalized: bool = False,
        input_clip: tuple[float, float] | None = (0.0, float('inf')),
        **kwargs,
    ):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        alpha_init : float | None
            Initial ``alpha``; must satisfy ``alpha > -1``; defaults to RandomNormal when None.
        alpha_trainable : bool
            Whether ``alpha`` is trainable.
        normalized : bool, default False
            When True, use orthonormal Laguerre polynomials (rescaled by the square root
            of the normalization constant). The standard form has norm
            :math:`\\Gamma(n + \\alpha + 1) / n!`.
        input_clip : tuple[float, float] | None
            Input clamp; defaults to ``(0.0, inf)`` for the natural domain :math:`[0, \\infty)`.
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

        self.alpha_init = alpha_init
        self.alpha_trainable = alpha_trainable
        self.normalized = normalized
        self.alpha_logits = None

        # Validate alpha_init at construction time if explicitly provided
        if alpha_init is not None and alpha_init <= -1.0:
            raise ValueError(
                f"GeneralizedLaguerre requires alpha > -1, got alpha_init={alpha_init}. "
                "The weight function x^alpha * exp(-x) is only integrable on [0, inf) for alpha > -1."
            )

    def build(self, input_shape):
        super().build(input_shape)
        self.alpha_logits = create_bounded_param_logits(
            self, "alpha", self.alpha_init, lower_bound=-1.0, trainable=self.alpha_trainable
        )

    @kan_fn
    def pseudo_vandermonde(self, x):
        # softplus_lower_bound ensures alpha > -1 with smooth gradients
        alpha = softplus_lower_bound(tf.cast(self.alpha_logits, x.dtype), lower_bound=-1.0)
        # :math:`L^{\alpha}_{0}(x) = 1`
        laguerre_basis = [tf.ones_like(x)]

        if self.degree > 0:
            # :math:`L^{\alpha}_{1}(x) = 1 + \alpha - x`
            laguerre_basis.append(1.0 + alpha - x)

        for n in range(1, self.degree):
            # :math:`(n+1) L_{n+1}^{\\alpha}(x) = (2n + 1 + \\alpha - x) L_n^{\\alpha}(x) - (n + \\alpha) L_{n-1}^{\\alpha}(x)`
            n_f = tf.cast(n, x.dtype)
            num = (2 * n_f + 1 + alpha - x) * laguerre_basis[n] - (n_f + alpha) * laguerre_basis[n - 1]
            laguerre_basis.append(num / (n_f + 1.0))

        basis = tf.stack(laguerre_basis, axis=-1)
        if self.normalized:
            # Norm: Γ(n + α + 1) / n!
            n = tf.range(0, self.degree + 1, dtype=basis.dtype)
            alpha_cast = tf.cast(alpha, basis.dtype)
            log_norm = tf.math.lgamma(n + alpha_cast + 1.0) - tf.math.lgamma(n + 1.0)
            scale = tf.exp(-0.5 * log_norm)
            basis = basis * scale
        return basis

    def clenshaw_basis(self, x: tf.Tensor) -> tf.Tensor:
        """
        Compute Laguerre basis using tf.scan for memory efficiency at high degrees.

        Uses the recurrence:
        :math:`L^{\\alpha}_{n+1}(x) = \\frac{(2n+1+\\alpha-x) L^{\\alpha}_n(x) - (n+\\alpha) L^{\\alpha}_{n-1}(x)}{n+1}`
        """
        x = tf.reshape(x, (-1, self.input_dim))
        # softplus_lower_bound ensures alpha > -1 with smooth gradients
        alpha = softplus_lower_bound(tf.cast(self.alpha_logits, x.dtype), lower_bound=-1.0)

        L0 = tf.ones_like(x)
        if self.degree == 0:
            return tf.expand_dims(L0, -1)
        L1 = 1.0 + alpha - x
        if self.degree == 1:
            return tf.stack([L0, L1], axis=-1)

        def step(carry, n):
            Ln_1, Ln_2 = carry
            n_f = tf.cast(n, x.dtype)
            # L_{n+1} = ((2n+1+alpha-x) L_n - (n+alpha) L_{n-1}) / (n+1)
            Ln = ((2.0 * n_f + 1.0 + alpha - x) * Ln_1 - (n_f + alpha) * Ln_2) / (n_f + 1.0)
            return (Ln, Ln_1)  # Only return new carry

        ns = tf.range(1, self.degree)  # n=1 gives L2, n=degree-1 gives L_degree
        carries = tf.scan(step, ns, initializer=(L1, L0))
        # carries[0] has shape (degree-1, batch, input_dim) - transpose to (batch, input_dim, degree-1)
        Ls = tf.transpose(carries[0], perm=[1, 2, 0])
        basis = tf.concat([tf.expand_dims(L0, -1), tf.expand_dims(L1, -1), Ls], axis=-1)
        if self.normalized:
            n = tf.range(0, self.degree + 1, dtype=basis.dtype)
            alpha_cast = tf.cast(alpha, basis.dtype)
            log_norm = tf.math.lgamma(n + alpha_cast + 1.0) - tf.math.lgamma(n + 1.0)
            scale = tf.exp(-0.5 * log_norm)
            basis = basis * scale
        return tf.reshape(basis, (-1, self.input_dim, self.degree + 1))

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "alpha_init": self.alpha_init,
                "alpha_trainable": self.alpha_trainable,
                "normalized": self.normalized,
            }
        )
        return config


# Aliases
Laguerre = GeneralizedLaguerre


__all__ = [
    "GeneralizedLaguerre",
    "Laguerre",
]
