# Copyright (c) 2025 René Schubotz. All rights reserved.
# Licensed under the terms specified in the LICENSE file in the project root.
r"""
Associated Meixner-Pollaczek polynomials.

This module implements the Associated Meixner-Pollaczek polynomials which are
orthogonal on the real line with respect to a weight given by the Meixner-Pollaczek
distribution.

Mathematical Background
-----------------------
The Associated Meixner-Pollaczek polynomials :math:`P_n^{(\lambda)}(x; \phi, c)` satisfy:

.. math::
    P_{-1}^{(\lambda)}(x; \phi, c) &= 0 \\
    P_0^{(\lambda)}(x; \phi, c) &= 1 \\
    P_{n+1}^{(\lambda)}(x; \phi, c) &= \frac{(2x\sin\phi + 2(n+c+\lambda)\cos\phi) P_n - (n+c+2\lambda-1) P_{n-1}}{n+c+1}

References
----------
.. [DLMF] NIST Digital Library of Mathematical Functions, §18.30
   https://dlmf.nist.gov/18.30#v
"""

import tensorflow as tf

from arnold.utils.compilation import kan_function
from arnold.utils.weights import create_trainable_param

from ..poly_base import PolynomialBase


tfk = tf.keras
kan_fn = kan_function()


@tfk.utils.register_keras_serializable(package="arnold", name="AssociatedMeixnerPollaczek")
class AssociatedMeixnerPollaczek(PolynomialBase):
    r"""
    Kolmogorov-Arnold Network layer using Associated Meixner–Pollaczek polynomials.

    Meixner-Pollaczek polynomials are orthogonal on the real line with respect to the weight function given by the Meixner-Pollaczek distribution.
    The Associated Meixner–Pollaczek polynomials are generated by the three-term recurrence relation:

    * :math:`P^{\lambda}_{-1}(x; \phi, c) = 0`
    * :math:`P^{\lambda}_{0}(x; \phi, c)  = 1`
    * :math:`P^{\lambda}_{n+1}(x; \phi, c) = \frac{(2 * x * \sin(\phi) + 2*(n + c + \lambda)* P^{\lambda}_{n}(x; \phi, c) - (n + c + 2*\lambda - 1) * P^{\lambda}_{n-1}(x; \phi, c)}{n + c + 1}, \, n >= 0`

    See also: https://dlmf.nist.gov/18.30#v
    """

    def __init__(
        self,
        degree: int,
        *,
        units: int,
        lambda_init: float | None = None,
        lambda_trainable=True,
        phi_init: float | None = None,
        phi_trainable=True,
        c_init: float | None = None,
        c_trainable=True,
        input_clip=None,
        **kwargs,
    ):
        r"""
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        lambda_init, phi_init, c_init : float | None
            Initial parameter values; default to RandomNormal when None.
        lambda_trainable, phi_trainable, c_trainable : bool
            Trainability flags.
        input_clip : tuple[float, float] | None
            Optional input clamp.
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

        self.lambda_init = lambda_init
        self.lambda_trainable = lambda_trainable
        self.phi_init = phi_init
        self.phi_trainable = phi_trainable
        self.c_init = c_init
        self.c_trainable = c_trainable

        self.lambda_ = None
        self.phi = None
        self.c = None

    def build(self, input_shape):
        super().build(input_shape)

        self.lambda_ = create_trainable_param(self, "lambda", self.lambda_init, trainable=self.lambda_trainable)
        self.phi = create_trainable_param(self, "phi", self.phi_init, trainable=self.phi_trainable)
        self.c = create_trainable_param(self, "c", self.c_init, trainable=self.c_trainable)

    @kan_fn
    def pseudo_vandermonde(self, x):
        # Cast trainable params to x.dtype to avoid dtype mismatch
        lambda_ = tf.cast(self.lambda_, x.dtype)
        phi = tf.cast(self.phi, x.dtype)
        c = tf.cast(self.c, x.dtype)

        # :math:`P^{\lambda}_{0}(x; \phi, c)  = 1`
        meixner_pollaczek_basis = [tf.ones_like(x)]

        if self.degree > 0:
            # \frac{(2 * x * \sin(\phi) + 2*(n + c + \lambda)}{n + c + 1}
            meixner_pollaczek_basis.append(
                (2 * x * tf.sin(phi) + 2 * (1 + c + lambda_) * tf.cos(phi)) / (1 + c + 1.0)
            )

        for n in range(2, self.degree + 1):
            # :math:`P^{\lambda}_{n+1}(x; \phi, c) = \frac{(2 * x * \sin(\phi) + 2*(n + c + \lambda)* P^{\lambda}_{n}(x; \phi, c) - (n + c + 2*\lambda - 1) * P^{\lambda}_{n-1}(x; \phi, c)}{n + c + 1}  when n >= 2
            term1 = 2 * x * tf.sin(phi) + 2 * (n + c + lambda_) * tf.cos(phi)
            term2 = n + c + 2 * lambda_ - 1.0
            term3 = n + c + 1.0
            meixner_pollaczek_basis.append(
                (term1 * meixner_pollaczek_basis[n - 1] - term2 * meixner_pollaczek_basis[n - 2]) / term3
            )

        return tf.stack(meixner_pollaczek_basis, axis=-1)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "lambda_init": self.lambda_init,
                "lambda_trainable": self.lambda_trainable,
                "phi_init": self.phi_init,
                "phi_trainable": self.phi_trainable,
                "c_init": self.c_init,
                "c_trainable": self.c_trainable,
            }
        )
        return config


__all__ = [
    "AssociatedMeixnerPollaczek",
]
