# Copyright (c) 2025 René Schubotz. All rights reserved.
# Licensed under the terms specified in the LICENSE file in the project root.
r"""
Pollaczek polynomials.

This module implements Pollaczek polynomials :math:`P_n(x; a, b)`.

Mathematical Background
-----------------------
The Pollaczek polynomials satisfy the three-term recurrence:

.. math::
    P_0(x; a, b) &= 1 \\
    P_1(x; a, b) &= (2a+1)x + 2b \\
    n P_n(x; a, b) &= [(2n-1+2a)x + 2b] P_{n-1} - (n-1) P_{n-2}, \quad n \geq 2

References
----------
.. [Mathworld] https://mathworld.wolfram.com/PollaczekPolynomial.html
"""

import tensorflow as tf

from arnold.utils.compilation import kan_function

from ..poly_base import PolynomialBase


tfk = tf.keras
kan_fn = kan_function()


@tfk.utils.register_keras_serializable(package="arnold", name="Pollaczek")
class Pollaczek(PolynomialBase):
    r"""
    Kolmogorov-Arnold Network layer using Pollaczek polynomials.

    The Pollaczek polynomials are generated by the three-term recurrence relation:

    * :math:`P_{0}(x; a, b) = 1`
    * :math:`P_{1}(x; a, b) = (2 * a + 1) * x + 2 * b`
    * :math:`P_{n}(x;a,b) = \frac{[(2n-1+2a)x+2b]P_{n-1}(x;a,b)-(n-1)P_{n-2}(x;a,b) }{n}, \, n \geq 2`

    See also: https://mathworld.wolfram.com/PollaczekPolynomial.html
    """

    def __init__(
        self,
        degree: int,
        *,
        units: int,
        a_init: float | None = None,
        a_trainable: bool = True,
        b_init: float | None = None,
        b_trainable: bool = True,
        input_clip=None,
        **kwargs,
    ):
        """
        Parameters
        ----------
        degree : int
            Maximum polynomial degree.
        units : int
            Output dimensionality.
        a_init, b_init : float | None
            Initial parameter values; default to RandomNormal when None.
        a_trainable, b_trainable : bool
            Trainability flags.
        input_clip : tuple[float, float] | None
            Optional input clamp.
        **kwargs :
            Forwarded to :class:`PolynomialBase`.
        """
        super().__init__(degree=degree, units=units, input_clip=input_clip, **kwargs)

        self.a_init = a_init
        self.a_trainable = a_trainable
        self.b_init = b_init
        self.b_trainable = b_trainable
        self.a = None
        self.b = None

    def build(self, input_shape):
        super().build(input_shape)

        def _init_param(v):
            if v is not None:
                return tfk.initializers.Constant(value=v)
            return tfk.initializers.RandomNormal(mean=0.0, stddev=1.0, seed=None)

        self.a = self.add_weight(initializer=_init_param(self.a_init), name="a", trainable=self.a_trainable)

        self.b = self.add_weight(initializer=_init_param(self.b_init), name="b", trainable=self.b_trainable)

    @kan_fn
    def pseudo_vandermonde(self, x):
        # Cast trainable params to x.dtype to avoid dtype mismatch
        a = tf.cast(self.a, x.dtype)
        b = tf.cast(self.b, x.dtype)

        # :math:`P_{0}(x; a, b) = 1`
        pollaczek_basis = [tf.ones_like(x)]

        if self.degree > 0:
            # :math:`P_{1}(x; a, b) = (2 * a + 1) * x + 2 * b`
            pollaczek_basis.append((2 * a + 1) * x + 2 * b)

        for n in range(2, self.degree + 1):
            # :math:`P_{n}(x;a,b) = \frac{[(2n-1+2a)x+2b]P_{n-1}(x;a,b)-(n-1)P_{n-2}(x;a,b) }{n} when n >= 2
            pollaczek_basis.append(
                (
                    ((2 * n - 1 + 2 * a) * x + 2 * b) * pollaczek_basis[n - 1]
                    - (n - 1) * pollaczek_basis[n - 2]
                )
                / n
            )

        return tf.stack(pollaczek_basis, axis=-1)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "a_init": self.a_init,
                "a_trainable": self.a_trainable,
                "b_init": self.b_init,
                "b_trainable": self.b_trainable,
            }
        )
        return config


__all__ = [
    "Pollaczek",
]
